export const VacanciesItems = [
  {
    solicitud: "3080154",
    cargo: "Asistente Administrativo",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion: "Conocimientos en áreas administrativas.",
    fechaPublicacion: "29/09/2021",
  },
  {
    solicitud: "3075573",
    cargo: "Auxiliar Servicios Generales y Cafeteria",
    educacion1: "Bachilleres",
    educacion2: "técnicos",
    descripcion:
      "Ejecutar funciones de servicios generales, mantenimiento y mensajeria eventual.",
    fechaPublicacion: "29/09/2021",
  },
  {
    solicitud: "3088821",
    cargo: "Técnico en Sistemas",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion:
      "Conocimientos en soporte y mantenimiento de Hardware, mantenimiento de computadores.",
    fechaPublicacion: "29/09/2021",
  },
  {
    solicitud: "3070925",
    cargo: "Auxiliar Hseq",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion: "Conocimientos  relacionados en SST.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3071918",
    cargo: "Auxiliar Administrativo",
    educacion1: "bachilleres",
    descripcion: "Experiencia relacionada a las áreas administrativas.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3075927",
    cargo: "Tecnólogo en Construcción",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion: "Experiencia en constructoras.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3075852",
    cargo: "Auxiliar de Oficina",
    educacion1: "bachilleres",
    educacion2: "técnicos",
    educacion3: "tecnólogos",
    descripcion:
      "Experiencia con actividades administrativas, manejo de correspondencia, organización de archivo.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3076159",
    cargo: "Asesor Call Center",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion: "Excelentes habilidad en atención a clientes.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3078850",
    cargo: "Salud Ocupacional y Seguridad",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion:
      "Experiencia en procesos sst y conocimiento en herramientas ofimáticas.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3080930",
    cargo: "Auxiliar Administrativo",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion: "Experiencia en áreas administrativas.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3081828",
    cargo: "Diseñador Grafico",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    descripcion:
      "Excelentes habilidades al trabajo en equiopo, responsabilidad y dominio de herramientas ofimáticas.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3079476",
    cargo: "Operador de Máquina Plana Collarín",
    educacion1: "bachilleres",
    educacion2: "técnicos",
    educación3: "tecnólogos",
    descripcion:
      "Conocimientos con manejo de máquina plana, fileteadora y collarín.",
    fechaPublicacion: "21/09/2021",
  },
  {
    solicitud: "3069822",
    cargo: "Administrador de Empresas",
    educacion1: "",
    educacion2: "",
    educacion3: "Profesional",
    descripcion:
      "Excelentes habilidades comunicativas y orientación al servicio.",
    fechaPublicacion: "01/09/2021",
  },
  {
    solicitud: "3069846",
    cargo: "Asesor Call Center",
    educacion1: "bachilleres",
    educacion2: "técnicos",
    educacion3: "tecnólogos",
    descripcion:
      "Con experiencia en ventas Call Center de seguros y/0 intangibles, en modalidad de teletrabajo. Indispensable contar con computador y conexión a internet",
    fechaPublicacion: "01/09/2021",
  },
  {
    solicitud: "3069847",
    cargo: "Asesor Comercial",
    educacion1: "bachilleres",
    educacion2: "técnicos",
    educacion3: "tecnólogos",
    descripcion:
      "Experiencia en ventas intangibles, en modalidad de teletrabajo.",
    fechaPublicacion: "01/09/2021",
  },
  {
    solicitud: "3052788",
    cargo: "Tecnólogo en Electrónica",
    educacion1: "técnicos",
    educacion2: "tecnólogos",
    educacion3: "profesionales",
    descripcion: "Conocimiento en soportes electrónico.",
    fechaPublicacion: "12/08/2021",
  },
];
export default VacanciesItems;
